version: "3.8"

services:
  example:
    build: .
  nats:
    image: nats:2.10.4-alpine
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - ./server.conf:/etc/nats/nats-server.conf
